//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<tb_ApproveState> tb_ApproveState { get; set; }
        public DbSet<tb_ApproveType> tb_ApproveType { get; set; }
        public DbSet<tbCSIHoliday> tbCSIHolidays { get; set; }
        public DbSet<tbl_ApproveRequest> tbl_ApproveRequest { get; set; }
        public DbSet<tbl_LeaveApprovers> tbl_LeaveApprovers { get; set; }
        public DbSet<tbl_LeaveRecords> tbl_LeaveRecords { get; set; }
        public DbSet<tbl_LeaveType> tbl_LeaveType { get; set; }
        public DbSet<tbl_LimitLeaveMaster> tbl_LimitLeaveMaster { get; set; }
        public DbSet<tbl_TimeAttendantImport> tbl_TimeAttendantImport { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblEmployeeOrganization> tblEmployeeOrganizations { get; set; }
        public DbSet<tblOrganization> tblOrganizations { get; set; }
        public DbSet<tblPart2Master> tblPart2Master { get; set; }
        public DbSet<tblPosition> tblPositions { get; set; }
        public DbSet<tblProject> tblProjects { get; set; }
        public DbSet<tblProjectMember> tblProjectMembers { get; set; }
        public DbSet<tbOnSiteEmployee> tbOnSiteEmployees { get; set; }
        public DbSet<tbSiteMaster> tbSiteMasters { get; set; }
        public DbSet<tbTimeAttendantUpdate> tbTimeAttendantUpdates { get; set; }
        public DbSet<tbl_TimeAttendantImportDetail> tbl_TimeAttendantImportDetail { get; set; }
    }
}
