//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ApproveState
    {
        public int AppStateNo { get; set; }
        public string AppStateCode { get; set; }
        public string Description { get; set; }
        public int AppStateOrder { get; set; }
        public Nullable<bool> RequestFlag { get; set; }
        public string AppFormatNo { get; set; }
        public int ModuleNo { get; set; }
        public bool IsObsoleted { get; set; }
    }
}
