//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TimeAttendantImportDetail
    {
        public int ImportID { get; set; }
        public int DetailID { get; set; }
        public string EmployeeID { get; set; }  = "890343";
        public string LeaveNo { get; set; }
        public byte[] EmployeeName { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; } 
        public string WorkOnSiteStart { get; set; }
        public string WorkOnSiteStop { get; set; }
        public string SiteStartTime { get; set; }
        public string SiteStopTime { get; set; }
        public string ProjectName { get; set; }
    }
}
