//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LimitLeaveMaster
    {
        public string LeaveType { get; set; }
        public int EmployeeType { get; set; }
        public int Gender { get; set; }
        public string WorkYear { get; set; }
        public string LeaveDay { get; set; }
        public Nullable<int> DivideFirstYear { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
