//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LeaveRecords
    {
        public string LeaveNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string EmployeeNo { get; set; }
        public string LeaveType { get; set; }
        public string LeaveOther { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> LeaveDtTmFrom { get; set; }
        public Nullable<System.DateTime> LeaveDtTmTo { get; set; }
        public Nullable<short> LeaveDay { get; set; }
        public Nullable<short> LeaveHour { get; set; }
        public Nullable<short> LeaveMin { get; set; }
        public string CCReceiver { get; set; }
        public Nullable<int> CurrentleaveState { get; set; }
        public string LeaveStatus { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> ProjectSiteCode { get; set; }
        public Nullable<byte> ProjectSiteAllowance { get; set; }
        public string EPS_LeaveNo { get; set; }
    }
}
