//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TimeAttendantImport
    {
    [Key]
        public int ImportID { get; set; }
        public string UploadBy { get; set; }  = "890343";
        public Nullable<System.DateTime> UploadDate { get; set; } = DateTime.Now;
        public Nullable<int> CurrentLeaveState { get; set; }
        public string LeaveStatus { get; set; }
    }
}
