//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public string EmployeeNo { get; set; }
        public Nullable<byte> TitleNo { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeFirstNameThai { get; set; }
        public string EmployeeLastNameThai { get; set; }
        public string EmployeeNickName { get; set; }
        public Nullable<byte> EmployeeType { get; set; }
        public Nullable<int> CompanyNo { get; set; }
        public Nullable<int> OrganizationNo { get; set; }
        public Nullable<int> PositionNo { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public string EmployeeEMail { get; set; }
        public Nullable<System.DateTime> QuitDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
