//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeOrganization
    {
        public string EmployeeNo { get; set; }
        public int OrganizationNo { get; set; }
        public int PositionNo { get; set; }
        public Nullable<byte> EmployeeOrganizationRate { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<System.DateTime> StartEffectiveDate { get; set; }
        public Nullable<System.DateTime> EndEffectiveDate { get; set; }
        public Nullable<bool> EmployeeOrganizationFlag { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string PrevEmployeeNo { get; set; }
    }
}
