//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganization
    {
        public tblOrganization()
        {
            this.tblProjects = new HashSet<tblProject>();
        }
    
        public int OrganizationNo { get; set; }
        public string OrganizationAlias { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string OrganizationCode { get; set; }
        public int OrganizationFlag { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ParentOrgNo { get; set; }
    
        public virtual ICollection<tblProject> tblProjects { get; set; }
    }
}
