//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectMember
    {
        public int SeqID { get; set; }
        public string ProjectID { get; set; }
        public short VersionNo { get; set; }
        public int Part2ID { get; set; }
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string MemberTypeCode { get; set; }
        public string PositionIncharge { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanFinishDate { get; set; }
        public Nullable<decimal> PlanEffortRate { get; set; }
        public Nullable<System.DateTime> AcctualStartDate { get; set; }
        public Nullable<System.DateTime> AcctualFinishDate { get; set; }
        public Nullable<decimal> AcctualEffortRate { get; set; }
        public Nullable<decimal> TransportFee { get; set; }
        public Nullable<decimal> OnSiteAllowance { get; set; }
        public Nullable<decimal> SpecialistFee { get; set; }
        public string OtherExpense { get; set; }
        public Nullable<System.DateTime> OnSiteStart { get; set; }
        public Nullable<System.DateTime> OnSiteFinish { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual tblPart2Master tblPart2Master { get; set; }
    }
}
