//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart2Master
    {
        public tblPart2Master()
        {
            this.tblProjectMembers = new HashSet<tblProjectMember>();
        }
    
        public int Part2ID { get; set; }
        public string FunctionCode { get; set; }
        public string Function { get; set; }
        public string Description { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual ICollection<tblProjectMember> tblProjectMembers { get; set; }
    }
}
