//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public string ProjectID { get; set; }
        public short VersionNo { get; set; }
        public string ProjectName { get; set; }
        public string ProjectNameAlias { get; set; }
        public string CustomerCode { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
        public Nullable<int> ProjectGroupID { get; set; }
        public int GroupOwnerID { get; set; }
        public string CSIGroupCompanyID { get; set; }
        public string CustomerCompanyID { get; set; }
        public string CustomerCompanyAlias { get; set; }
        public string EndUserCompanyID { get; set; }
        public Nullable<decimal> TransportationFee { get; set; }
        public Nullable<decimal> HotelAllowance { get; set; }
        public Nullable<decimal> TravelingExpense { get; set; }
        public string StatusCode { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ContractTypeNo { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> OnSiteWorkHr { get; set; }
        public Nullable<int> DefaultOnsiteWorkCalendarSeqNo { get; set; }
        public Nullable<System.DateTime> StartDatePlan { get; set; }
        public Nullable<System.DateTime> FinishDatePlan { get; set; }
        public Nullable<System.DateTime> StartDateActual { get; set; }
        public Nullable<System.DateTime> FinishDateActual { get; set; }
        public Nullable<System.DateTime> WaranteeStartDatePlan { get; set; }
        public Nullable<System.DateTime> WaranteeFinishDatePlan { get; set; }
        public Nullable<System.DateTime> WaranteeStartDateActual { get; set; }
        public Nullable<System.DateTime> WaranteeFinishDateActual { get; set; }
        public string ProjectRefDoc { get; set; }
        public Nullable<int> SMCProjectID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
    }
}
