//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOnSiteEmployee
    {
        public int RunningID { get; set; }
        public int EmployeeID { get; set; }
        public int SiteID { get; set; }
        public string StartOnSite { get; set; }
        public string StopOnSite { get; set; }
        public int LocationOnSite { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tbSiteMaster tbSiteMaster { get; set; }
    }
}
