//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSiteMaster
    {
        public tbSiteMaster()
        {
            this.tbOnSiteEmployees = new HashSet<tbOnSiteEmployee>();
        }
    
        public int SiteID { get; set; }
        public string SiteName { get; set; }
        public int ManagerID { get; set; }
        public string SiteStartTime { get; set; }
        public string SiteStopTime { get; set; }
        public string WorkOnSiteStart { get; set; }
        public string WorkOnSiteStop { get; set; }
        public bool DeleteFlag { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int UserID { get; set; }
        public string StartLunch { get; set; }
        public string EndLunch { get; set; }
    
        public virtual ICollection<tbOnSiteEmployee> tbOnSiteEmployees { get; set; }
    }
}
