//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAttPlus.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTimeAttendantUpdate
    {
        public int TimeAttendantID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> SystemIN { get; set; }
        public Nullable<System.DateTime> SystemOUT { get; set; }
        public Nullable<System.DateTime> HRMIN { get; set; }
        public Nullable<System.DateTime> HRMOUT { get; set; }
        public string SiteStartTime { get; set; }
        public string SiteStopTime { get; set; }
        public int SiteAllowance { get; set; }
        public string Remark { get; set; }
        public bool Complete { get; set; }
        public int ManualAllowance { get; set; }
        public int SiteID { get; set; }
        public Nullable<System.DateTime> WorkOnSiteIN { get; set; }
        public Nullable<System.DateTime> WorkOnSiteOUT { get; set; }
        public string WorkOnSiteStart { get; set; }
        public string WorkOnSiteStop { get; set; }
        public Nullable<System.DateTime> LFMUpdated { get; set; }
        public string LeaveNo { get; set; }
        public Nullable<short> TransportFeeTypeID { get; set; }
        public Nullable<byte> NoLateFlag { get; set; }
    }
}
